### ISSUE TITLE
Не работает gate-simulator

### ISSUE THREAD

**Issue by supremko** [supremko/diplom#1]
1. В docker-compose настроил запуск контейнера с Node.js
```
  node:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./gate-simulator:/home/node/app
    expose:
      - "8081"
    command: "npm start"
```
2. Запустил контейнер
3. Ввел команду docker-compose exec node npm start
4. Отобразился лог
```
> gate-simulator@1.0.0 prestart /home/node/app
> npm i

npm WARN gate-simulator@1.0.0 No description
npm WARN gate-simulator@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux
","arch":"x64"})

audited 268 packages in 2.117s
found 0 vulnerabilities


> gate-simulator@1.0.0 start /home/node/app
> nodemon app.js

[nodemon] 2.0.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
[
  { number: '4444 4444 4444 4441', status: 'APPROVED' },
  { number: '4444 4444 4444 4442', status: 'DECLINED' }
]
```
5. Ввел данные карты, по которой должен быть апрув
![image](https://user-images.githubusercontent.com/505723/72021097-48fc8c00-327e-11ea-9328-f6ee685abb81.png)
6. Получил ошибку 500 и, соответственно, запрет операции покупки
![image](https://user-images.githubusercontent.com/505723/72021182-806b3880-327e-11ea-9ed1-196bd205ab1d.png)

При этом в логах SUT ошибка
```
2020-01-09 01:15:55.486 ERROR 30480 --- [nio-8080-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherSer
vlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.client.ResourceAccessExcept
ion: I/O error on POST request for "http://localhost:7777/payment": Connection refused: connect; nested exception is java.net.ConnectException: C
onnection refused: connect] with root cause
```
На порту 9999 gate-simulator вообще не запускался, поменял в app.js на 7777 и запуск прошел без ошибок, но не работает.
